### ISSUE TITLE
IzzyOnDroid inclusion

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/ConnectYou#1]
Hey @IzzySoft,
in the last days I've been creating yet another app because I couldn't find a good open source alternative for it.
This time it's about managing your phone's contacts, which should hopefully be more useful than an automatically changing wallpaper :wink:

So, it would be awesome if you could consider adding the app to your repo as well, to let some others benefit from it too.
That should be the first of my apps without any anti features as it doesn't connect to the internet and thus can't use non-free-nets :)
What's currently still missing in the `fastlane` structure are screenshots, I might add them sooner or later, but not for now. Adding changelogs to the `fastlane` structure is not planned this time.

Have a good one!

**Comment by IzzySoft** [comment]
Believe it or not, but I was eying this repo already for the last 2..3 days waiting for it to become ready :see_no_evil: 

> So, it would be awesome if you could consider adding the app to your repo as well,

already done, will show up with the next sync. No AntiFeatures, right. Just let me know when the screenshots are up, so I enable them for my updater.

**Comment by Bnyro** [comment]
> Believe it or not, but I was eying this repo already for the last 2..3 days waiting for it to become ready
> 
Oh wow, that's awesome, didn't foresee that! :) Though I wonder how you found the app as it's only been a pretty empty repo for the last few days, you must have found it within a day after it got created :joy:

Thanks for already including it to your repo, your support is really great! <3

**Comment by Bnyro** [comment]
Oh, what I also forgot to mention is that the current website address of me at your repo (bnyro.ga) is not reachable anymore, instead it's located at https://bnyro.is-a.dev now.
Would be great if you could change that too (since I think I can't change it).

**Comment by IzzySoft** [comment]
> Though I wonder how you found the app

Pssst, top secret:

![image](https://user-images.githubusercontent.com/6781438/214966303-f996aec3-e2a4-4989-a927-4d1248aee90b.png)

> you must have found it within a day after it got created

Very likely, yes. My agents report such things quickly :see_no_evil:

> Thanks for already including it to your repo, your support is really great! <3

:heart_eyes: 

> the current website address of me at your repo (bnyro.ga) is

… updated for all your apps now, thanks!

**Comment by TPS** [comment]
@Bnyro Would you consider requesting inclusion in the main F-Droid repo?

**Comment by Bnyro** [comment]
> @Bnyro Would you consider requesting inclusion in the main F-Droid repo?
>
Currently not, I'm happy with the technical support by Izzy and I feel like the community using Izzy's repo is more friendly and helpful than the one from the normal F-Droid repo.
Apart from that, I already added one app to F-Droid, which declined in popularity afterwards, so I don't really think that would be helpful for the app's future.

**Comment by darhma** [comment]
@Bnyro if the app does not need to be modified for inclusion in the official f-droid repo, in my opinion, it is a bit of a shame not to include it. Personally, I prefer to use apps from the official repo, although I do use the izzyondroid repo for some apps that are not present. In the end, I think you can keep both versions, as for example happens with catima and some other apps. Then of course the choice remains with you, but I see no particular downside.

**Comment by Bnyro** [comment]
I get your point, though I think I read apps need to exist for at least 3 months before they can get added to F-Droid (currently we're at day 6 starting from the project creation).
Apart from that I don't really like the delay for publishing new updates when using F-Droid, since I prefer if bug fixes roll out in within a day instead of after a week.

**Comment by IzzySoft** [comment]
> I read apps need to exist for at least 3 months before they can get added to F-Droid

Never heard such thing (though it has some reasoning in it).

> I don't really like the delay for publishing new updates when using F-Droid

Perfect solution to that: achieve reproducible builds and have your app listed in both repos. With RBs, F-Droid would include the APK signed by you, so cross-updates with my repo or even your Github releases would be possible. WWW aka Win-Win-Win: You have faster updates (via my repo), @darhma can install from F-Droid.org directly, and everybody is happy :smiley:

Just a suggestion, no pressure intended :wink:

**Comment by Bnyro** [comment]
> Never heard such thing (though it has some reasoning in it).
> 
I've been trying to find it but there doesn't seem to be anything about that in the official F-Droid docs, so I've probably messed something up.
> Perfect solution to that: achieve reproducible builds and have your app listed in both repos. With RBs, F-Droid would include the APK signed by you, so cross-updates with my repo or even your Github releases would be possible. WWW aka Win-Win-Win: You have faster updates (via my repo), @darhma can install from F-Droid.org directly, and everybody is happy :smiley:
> 
I've looked at the F-Droid documentation about it and the length of the article is already making me a bit scared. If I understood it correctly that requires some additional steps when building new releases, or does it only have to be done once and then works as any normal building process? I don't really want to overcomplicate things, but if you think it's a quick and doable process then we should consider it :)

**Comment by IzzySoft** [comment]
> I've been trying to find it but there doesn't seem to be anything about that in the official F-Droid docs, so I've probably messed something up.

I think so. Being one of the F-Droid maintainers for some years now I should know if such a condition would exist :rofl:

> or does it only have to be done once and then works as any normal building process?

That, if things go well. There might be hick-ups from time to time which require some adjustments (eg. if you switched to a newer NDK/SDK, or used a very fresh new gradle version not yet available at F-Droid), but basicaly it's intended to be rather set-and-forget. The process improved a lot in the past few weeks even – so even I managed to get some RBs set up :zany_face:

> I don't really want to overcomplicate things, but if you think it's a quick and doable process then we should consider it :)

I cannot promise rose gardens, and getting it set up to begin with might require some work (or simply work out-of-the-box, one never knows before one tries) – but if it's not too much hazzle (there were cases where we had to give up), I'd say it's worth it. Should definitely worth trying – you can always bail out :rofl:

**Comment by Bnyro** [comment]
> I cannot promise rose gardens, and getting it set up to begin with might require some work (or simply work out-of-the-box, one never knows before one tries) – but if it's not too much (there were cases where we had to give up), I'd say it's worth it. Should definitely worth trying – you can always bail out
>
Alright, thanks, that's something I'll look into in the weekend then :)

I've also added phone screenshots now, would be great if you could add them to your repo too.
Thanks in advance!

**Comment by IzzySoft** [comment]
Done. Screenshots look great! And :crossed_fingers: for the RFP then!
