### ISSUE TITLE
Dialer app issue when set to use Koler app

### ISSUE THREAD

**Issue by scottbetza** [Bnyro/ConnectYou#101]
### Steps to reproduce

1. Open app
2. Press contact to view
3. Press phone number to call

### Expected behavior

Open default phone app with number to call

### Actual behavior

When using [Koler](https://github.com/Chooloo/koler) as default dialer, the dialer never opens. 

Note that Connect You works fine with stock [Phone app](https://play.google.com/store/apps/details?id=com.google.android.dialer) and [Simple Dialer](https://github.com/SimpleMobileTools/Simple-Dialer).

### Connect You version

2.3 (14)

### Android version

Android 13 TQ1A.230205.002

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I use Koler too myself and it works flawlessly for me. However, I am using Koler version 1.5.0 and just saw there has been an update recently, so I'd assume that the latest update of Koler just broke it (assuming you updated to its latest version).
Thus, rather a Koler issue than ours.

**Comment by Bnyro** [comment]
That's very weird, I'm using the same Android version as you as well as the same Koler + Connect You version and still there are different results :/
In general Koler, the stock phone app and simple dialer should work all exactly the same way, so I've no clue why it doesn't for you unfortunately.

**Comment by scottbetza** [comment]
Opened issue on koler git.

See https://github.com/Chooloo/koler/issues/520
