### ISSUE TITLE
[FEATURE REQUEST] Add direct dial widget for home screen shortcuts

### ISSUE THREAD

**Issue by user8446** [Bnyro/ConnectYou#103]
Hi,

I would like to move from Contacts to ConnectYou and noticed that widgets are not supported. I have many direct dial shortcuts on my homescreen. A simple 1x1 shortcut would be a great add for ConnectYou.

Thank you 

### Other details

![Screenshot_20230313-121048](https://user-images.githubusercontent.com/18019245/224760966-0961fd0b-731a-4ff0-bc61-b4b2eb7b7f77.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by user8446** [comment]
Hi @Bnyro thank you for adding this. However, I just updated to v2.4 and on my Android 10 device it still does not show Connect You being able to add direct dial homescreen shortcuts.

**Comment by Bnyro** [comment]
Navigate to the contact you wish to create a shortcut for and create it via the button at the top right.
