### ISSUE TITLE
New contacts are added to  wrong Acccount

### ISSUE THREAD

**Issue by Tobias-Lauerbach** [Bnyro/ConnectYou#104]
### Steps to reproduce

1. Add a DavX5 account (davX5 app)
2. Create a new contact in CY 
3. select the account ("Kontotyp")
4. Save new contact

### Expected behavior

Contact is added to the selected Account (-> and synced via davX5 )

### Actual behavior

The new Contact is added to new Account (See Picture)
(AOSP Contacts recognize the new account as Davx5 but in DavX5 it dosen´t show up and the contact is not synced to the Server)

### Connect You version

2.3 (14)

### Android version

Android 13 CalyxOS Pixel5

### Expected Account

![Screenshot_20230313-202043](https://user-images.githubusercontent.com/62332598/224814034-a57de1da-dfab-4f35-b3b8-c12c44f37f39.png)

### New Account

![Screenshot_20230313-202033](https://user-images.githubusercontent.com/62332598/224814027-00c856f2-8cb5-40ef-8737-9ab1a8ffc212.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Oh damn, that's been an avoidable error, caused by copy and paste.
