### ISSUE TITLE
ConnectYou loads very slowly

### ISSUE THREAD

**Issue by PranavPurwar** [Bnyro/ConnectYou#105]
### Steps to reproduce

1. Open App

### Expected behavior

It should quickly load the contact list, preferably within 1-2 seconds

### Actual behavior

It takes more than 6 seconds for it to actually load all the stuff

### Connect You version

Both 2.3 and latest debug

### Android version

Android 9

### Other details

I'm actually switching from Google Contacts (never found any good material you open source alternative lol), while that loads with a second, ConnectYou takes like 5-6 seconds on every launch which is a bit annoying. Maybe cache all the contacts and update them lazily on app start? I've around 1.4k contacts (I'm logged on a bunch of accounts). Thanks for this cool project btw.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by PranavPurwar** [comment]
I would also like to ask about how the downloads badge in the readme pull data from fdroid

**Comment by Bnyro** [comment]
> I would also like to ask about how the downloads badge in the readme pull data from fdroid
>
What do you mean?

**Comment by PranavPurwar** [comment]
There's a badge in the readme that shows the number of people that have downloaded this project (from fdroid using IzzyOnDroid repo), I wanna ask how you set it up

**Comment by PranavPurwar** [comment]
Thanks! At first I thought that it used to fetch that from IzzyOnDroid repo

**Comment by Bnyro** [comment]
Oh right, got you.
Unfortunately I don't think it's possible to obtain these stats from F-Droid or IzzyOnDroid.
