### ISSUE TITLE
Change the app name in the app drawer. 

### ISSUE THREAD

**Issue by Klejdi-Bozho** [Bnyro/ConnectYou#112]
### Describe your suggested feature

The app should have a more generic name in the app drawer, like "Contacts" . It is the same thing that simple contacts and google contacts do. I feel it would fit better. I am not saying change the name of the project. You could do something similiar to the developer of opencalc, where the app is named opencalc in fdroid and simply calculator in the app drawer. 

### Other details

![Screenshot_20230318-173115_1](https://user-images.githubusercontent.com/127548208/226120231-687e7131-e428-48bd-ad70-a37bd0c31ea7.png)
![Screenshot_20230318-173110](https://user-images.githubusercontent.com/127548208/226120236-dbc9d0be-b22a-4f5f-8702-1136e2f63581.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by githububub** [comment]
A nice side effect of this would be eliminating the label ellipses for the home screen icon for certain devices where the default screen font/zoom results in label overflow e.g. Pixel 6/Pixel 7 GOS.

**Comment by Bnyro** [comment]
I don't like the idea because
1. it makes it harder to distinguish between contact apps if you have multiple installed
2. it may be confusing to new users to not find the app as `Connect You`
3. the `You` wouldn't be visible anymore, however that the `You` can somewhat be used to identify apps made by me
