### ISSUE TITLE
Colourised bars?

### ISSUE THREAD

**Issue by AntonDzutstsati** [Bnyro/ConnectYou#113]
### Describe your suggested feature

Is it possible to colourise status bar and navigation bar in Contact, Settings and Editor pages?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Yes, but why should we?
