### ISSUE TITLE
Random contacts disappear after latest update

### ISSUE THREAD

**Issue by HarriBuh** [Bnyro/ConnectYou#114]
### Steps to reproduce

1. Update app to 2.4
2. Open app
3. Look for formerly available contacts
4. Wonder

### Expected behavior

Formerly saved and properly backed up contacts should be available at all times.

### Actual behavior

I have to manually create the lost contacts again. After I did this and entered edit mode, the old stats like phone numbers appeared again, together with the freshly entered number.

### Connect You version

2.4.0

### Android version

13.0

### Other details

Google Pixel 7
Android 13
Root w/ Magisk Delta.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In fact nothing about how contacts are being fetched has been changed within the update. 
Device contacts are not stored inside the app, so an update can't "delete" any of your contacts, and there's no way the latest update removed some already existing contacts.
Make sure you don't have any third party app on your phone accessing and modifying your contacts!
