### ISSUE TITLE
Sorting contacts is broken

### ISSUE THREAD

**Issue by airon90** [Bnyro/ConnectYou#12]
You can sort contacts by first name or by surname, as labels say, but first one sorts contacts in a random way  (I really don't understand how it works) while second one sorts contacts by family name.

Moreover, if you choose the second kind of sort and you close the app, it doesn't remember your choice so when you reopen the app it sorts contacts by first kind of sort.

**Comment by Bnyro** [comment]
I can't reproduce your issue that sorting by first name doesn't work.
