### ISSUE TITLE
Add dialler (keypad)

### ISSUE THREAD

**Issue by xmha97** [Bnyro/ConnectYou#124]
### Describe your suggested feature

Hi, Connect You is default contact app.
Please add dialler (keypad).
Although it may seem out of scope.
As in the "Record You" app, a screen recorder app was combined with a sound recorder app, the combination of "Phone" app and "Contacts" app is also wonderful. (Like Truecaller app)
Thanks 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned, please consider using Koler instead.

**Comment by xmha97** [comment]
Thanks, Koler is good dialer.
