### ISSUE TITLE
Put favorite contacts in separate section.

### ISSUE THREAD

**Issue by matt1432** [Bnyro/ConnectYou#128]
### Describe your suggested feature

I love this app but the only thing stopping me from switching over is not having my favorite contacts in a separate section above the alphabetically ordered ones.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I currently don't plan to support favorited contacts. You can just create a contacts group for that.

**Comment by ashpieboop** [comment]
What about the feature that allows "Starred contacts" to bypass Do Not Disturb mode ?
