### ISSUE TITLE
Date events should use DatePicker

### ISSUE THREAD

**Issue by airon90** [Bnyro/ConnectYou#13]
Date events, such as birthdays and anniversary (and death, I would add it), should use DatePicker or something like that, in order to enter correct dates in a friendly way

**Comment by Bnyro** [comment]
I agree, unfortunately Jetpack Compose doesn't support date pickers yet so I will need to find a way to work around the issue and use the traditional version of it.

**Comment by airon90** [comment]
Ok, just one question as I didn't try. Does the app prevent me to insert something wrong or misunderstandable, i.e. 2022-02-30 (it doesn't exist) 25-12-2022 (not in ISO format) or 05-02-2023 (5th of February or 2nd of May?)?

**Comment by Bnyro** [comment]
Currently you can insert anything you want which is an issue, yes, I agree that that should really be improved.

**Comment by Bnyro** [comment]
https://github.com/Bnyro/ConnectYou/commit/600d2ad4466de62e3c5e01392b9f267ced7e3dd9
