### ISSUE TITLE
Adding contacts sucks

### ISSUE THREAD

**Issue by pabloscloud** [Bnyro/ConnectYou#130]
### Steps to reproduce

Open Signal for example and click on "Add to Contacts" in the contact embed.

### Expected behavior

Should populate all information, like:
First name,
Last name,
Emails,
Phone numbers,
Addresses,
Birthday,
..

### Actual behavior

Just populates the phone number but nothing else (not even a name)

### Connect You version

3.0 (17)

### Android version

13

### Other details

CalyxOS 4.7.5

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
In fact #129 is about the same issue.

**Comment by pabloscloud** [comment]
I thought #129 was just about the phone number. There is all kind of information that's missing tho. Take a look

**Comment by Bnyro** [comment]
All the supported fields by Android should be supported by CY now too in that manner.
Please feel free to test the latest debug build as I'm not exactly sure if it works as intended now since none of the apps I use provides the ability to create new contacts by already sharing some information!
