### ISSUE TITLE
[Bug] Wrong date after selection

### ISSUE THREAD

**Issue by pabloscloud** [Bnyro/ConnectYou#138]
### Steps to reproduce

1. Add an event to a contact
2. Set it to the current one
3. See that it's not today but yesterday

### Expected behavior

The correct date is saved

### Actual behavior

The day before the selected date is saved

### Connect You version

3.0

### Android version

13

### Other details

CalyxOS 4.7.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by brendanfattig** [comment]
This is still an issue in version 5.0 installed from Accrescent. Seems to be somewhat related to time zones. Using time zone greater than or equal to +0 of UTC shows the correct date in the edit contact view but one day before in the contact details view. However, a system time zone set to less than +0 of UTC shows one day before in both the edit contact view and the contact details view.
