### ISSUE TITLE
Address should open apps

### ISSUE THREAD

**Issue by airon90** [Bnyro/ConnectYou#14]
I don't know how you could implement this but I suppose it is better if you can make address clickable so that one can search it on their own favourite map app

**Comment by airon90** [comment]
It doesn't work, neither with OsmAnd nor with Google Maps

**Comment by Bnyro** [comment]
According to https://developer.android.com/guide/components/intents-common#Maps
it should work, we're doing it exactly the same way. Idk what the issue is.

**Comment by airon90** [comment]
Is it maybe because of how your app handles address, house number, postcode and city? Maybe you should know that I use Nextcloud and DAVx5 in order to sync my contacts
