### ISSUE TITLE
Request to change app name to "Contact You"

### ISSUE THREAD

**Issue by meenbeese** [Bnyro/ConnectYou#146]
### Describe your suggested feature

I am writing to propose a change in the name of your contacts application from "Connect You" to "Contact You". The current app name may suggest a networking or social media application, which may confuse users who are looking for a simple contacts application. The new name "Contact You" is more straightforward and descriptive of the app's core functionality.

As a contacts application, the primary purpose of your app is to help users manage and organize their contacts. However, the current name "Connect You" may not clearly convey this functionality to potential users. By changing the app name to "Contact You", users will have a better understanding of what the app does and how it can benefit them.

### Other details

I understand that changing the name of an established app can be a complex process, and I am only requesting permission to proceed with this change. If accepted, I am willing to submit a pull request to implement the new name in the app and deal with all the technicalities that come with it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for your interest in that!

However, first of all this would not only require changing it here, but also on IzzyOnDroid, the repo name, ...
The reasons why I don't want to rename the app are the following:
* "Contact You" sounds like you contact yourself?
* "connect" should indicate that the app is a way to keep connected with others, what a contacts app does in fact by keeping all your connections organized
* In my opinion, the app icon is expressive enough to indicate that the app is for contacts, even if the app name gets misunderstood
* Existing users might be confused by the new app name

I hope you get some of my reasons and can go on living with the current app name :)

**Comment by meenbeese** [comment]
I understand, thank you for your consideration anyway.
