### ISSUE TITLE
[Feature Request] Tablet UI Layout

### ISSUE THREAD

**Issue by JoeJoeTV** [Bnyro/ConnectYou#147]
### Describe your suggested feature

I would like to propose adding an option that enables a Tablet UI Layout for tablets or devices with larger screens that are mostly used in a landscape orientation.
This could have a slimmer contacts list on the left/right where one can scroll through the contacts and if a contact is selected, it opens on the right side/pane with the options related to the contact just like the new page that opens when tapping on a contact right now.

### Other details

An open source contacts app that looks nice and has more features than the bare minimum is something I've wanted for some time and Simple Contacts only recently started looking nicer, so would like to see this project flourish. Thanks for the work so far!

Maybe add a toggle in the setting for people that want still use the other layout either due to preferences or weird screen layouts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion.
However I won't work on that as I don't have a tablet myself so I wouldn't benefit from it myself. If you have an idea of Android development, feel free to create a PR for that, otherwise not planned from my side.
