### ISSUE TITLE
Integration with IM apps

### ISSUE THREAD

**Issue by airon90** [Bnyro/ConnectYou#15]
It would be nice to have instant messaging integration (i.e. direct link to Telegram, Whatsapp, ...)

**Comment by Bnyro** [comment]
I don't want to add direct links for specific messenger apps for the reason that any app needs explicit support, so there would need to be an explicit function checking for WhatsApp and opening it, an other one for Telegram, etc... I don't want to only support some IM apps, apart from that WhatsApp and Telegram were the last ones I'd liked to support.

SMS and Dialing actions that are already supported are app independent, so any dialer or SMS app is supported.
However, unfortunately that's not possible for instant messaging apps.
Thus, not planned.
