### ISSUE TITLE
Bad scroll slider

### ISSUE THREAD

**Issue by guglovich** [Bnyro/ConnectYou#150]
### Steps to reproduce

1. Start winding the contacts with your finger
2. Hold the slider and try to move it

### Expected behavior

Movement of the list together with the slider

### Actual behavior

The slider does not respond to your finger

### Connect You version

3.1 (18)

### Android version

13.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, this is not yet possible in Jetpack Compose.
