### ISSUE TITLE
Separate tab for "Contact Groups"

### ISSUE THREAD

**Issue by harishkumarankr2004** [Bnyro/ConnectYou#153]
### Describe your suggested feature

I would like to have a separate tab for Contact <b>Groups</b> so it would be much easier to categorise the contacts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that, in my opinion the current way works well enough.
