### ISSUE TITLE
Toggle to Disable Local Contacts 

### ISSUE THREAD

**Issue by harishkumarankr2004** [Bnyro/ConnectYou#154]
### Describe your suggested feature

Add a toggle to disable Local Contacts for people who never use it.
Also remove the unnecessary tab below along with it in the app.

### Other details

This seems important because there are only two groups of people here - who use local contacts and who don't.
It's important to cover both the user cases.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Both use cases are covered by allowing to choose the start tab. I don't see a reason to allow disabling it.
