### ISSUE TITLE
Back on search bar quits the app.

### ISSUE THREAD

**Issue by ghost** [Bnyro/ConnectYou#155]
### Steps to reproduce

1) Click the search bar
2) press the back gesture/button

### Expected behavior

The app should get out of the search function

### Actual behavior

The app quits itself

### Connect You version

3.1

### Android version

13

### Other details

I am also not sure if it's a bug or just how it was made to work.
It's the same way on accrescent too which was also made  by Bnyro, so not sure.
Whatever it is, it's not great for the end user.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
This would be doable, but quite a low priority atm.
