### ISSUE TITLE
Pill shaped Contact Profile Photos

### ISSUE THREAD

**Issue by harishkumarankr2004** [Bnyro/ConnectYou#159]
### Describe your suggested feature

The circular <b>Contact Profile Photos</b> could be made pill shaped.
The new material you (m3) design matches very much with pill shaped icons than circular icons.
When I went to the edit screen, it looked much better since the icon was pill shaped, make the <b>Contact Details</b> screen to have the same along with the <b>Contact List</b> screen, it matches with the pill shaped buttons and lists.

### Other details

You can have a look at the GrapheneOS's Apps app which also does this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I agree on generally preferring pill shapes than circles, however I don't believe it's a good choice for the contacts list since all other contact apps use circles and hence profile pictures are also made to fit into circles, not pills.
