### ISSUE TITLE
Contacts remove made by connect you

### ISSUE THREAD

**Issue by gun4qmm7h** [Bnyro/ConnectYou#160]
### Steps to reproduce

Happens randomly but this is what I do.
Open qksms
Add a contact using qksms
After a while (weeks) all contact made by connect you are removed.
This happens at random time.

### Expected behavior

Keeps my contact

### Actual behavior

Delete my contact

### Connect You version

3.1

### Android version

Grapheneos

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I used the app for months now already and never experienced something similar. I'd assume something else than Connect You is causing that.

**Comment by Bnyro** [comment]
I don't think so, they're stored in the Android contacts storage.

**Comment by junkminerman** [comment]
I would like to echo that I am also experiencing this issue, however, it seems to affect all my contacts. Connect You is installed through accrescent on GrapheneOS
