### ISSUE TITLE
Clicking on a contact take me to the app

### ISSUE THREAD

**Issue by gun4qmm7h** [Bnyro/ConnectYou#171]
### Steps to reproduce

Open phone app.
Click on contact
Results: Open the app without the the contact automatic selected

### Expected behavior

Open the app with the the contact automatic selected

### Actual behavior

Open the app without the the contact automatic selected

### Connect You version

4.0

### Android version

Android 13 grapheneos

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screen recording, I can't follow your steps.

**Comment by gun4qmm7h** [comment]
I was just about to make a screen recording of the issue. But then I got an email about the new update. Thank you for the fast update fix
