### ISSUE TITLE
Clicking on call open phone app with number instead of calling number at the start

### ISSUE THREAD

**Issue by gun4qmm7h** [Bnyro/ConnectYou#172]
### Steps to reproduce

Open connect you and click on call.

### Expected behavior

Call's on start when user clicks on the call button

### Actual behavior

Open the phone app with the number inputed but not dialed

### Connect You version

4.0

### Android version

Android 13 grapheneos

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's working as intended.

**Comment by gun4qmm7h** [comment]
Can you add it as an options to call on click?

**Comment by Bnyro** [comment]
No, that requires additional permissions
