### ISSUE TITLE
Crash when opening the app

### ISSUE THREAD

**Issue by Toine51** [Bnyro/ConnectYou#173]
### Steps to reproduce

Open the app

### Expected behavior

This should open the app

### Actual behavior

It is crashing as soon as i open it

### Connect You version

4.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Toine51** [comment]
![Screenshot_20230527-090103~2](https://github.com/Bnyro/ConnectYou/assets/134766617/ff468f21-a755-4723-94e5-0c8b582eea23)

**Comment by Bnyro** [comment]
#174
