### ISSUE TITLE
Bug: Contact Images not shown when opening the Contact out of the Contact Overview List

### ISSUE THREAD

**Issue by just-Nob** [Bnyro/ConnectYou#177]
# Description:

While the contact images are all visible in the overview, there's no image visible when opening the contact by tapping on one of them to show the contract's details.

I'm using [MyLocalAccount](https://play.google.com/store/apps/details?id=com.fjsoft.mylocalaccount&gl=DE) to store my contacts for not being forced to store them in my Google account and to sync them with the Google cloud.
(BTW: MyLocalAccount is fine when using MyPhoneExplorer.)

All other contact apps deal fine with the contact images.

# How to reproduce:

1. Install [MyLocalAccount](https://play.google.com/store/apps/details?id=com.fjsoft.mylocalaccount&gl=DE). (I'm going to check of that is really necessary.)
2. Add an account including an image.
3. Check that the image is visible in the Contact overview list.
4. Trap on the contact to check of the image is visible in the contract's detail view.

# Environment:

- Poco X3 (surya)
- Android 11 (ArrowOS Vanilla, Custom ROM without Google Play Services)
- microG (replacement for Google Play Services)
- rooted with Magisk

**Comment by just-Nob** [comment]
I see the "app" artifact with size being shown (15.6 MB) and tried to download, but neither with Firefox, nor with Bromite I wasn't able to detect a link (both on Android).

**Comment by Bnyro** [comment]
You need to be logged in order to be able to download it.

**Comment by just-Nob** [comment]
Thx, when being logged in, the download worked without any problems. ;)
Sorry for my request.

Problem seems to be solved by your changes, debug version works fine.

Btw, I recognized that even in the "non-debug" release there are some contacts that seem to work with that version as well, some others don't. I don't know what this is dependent of.
Anyway, with the debug app, they all seem to work.

Thx!

**Comment by Bnyro** [comment]
Great to hear, you're welcome!
I'll publish a new release in the next days!

**Comment by just-Nob** [comment]
Thanks, in looking forward to the next release! :)
