### ISSUE TITLE
Merge Contacts

### ISSUE THREAD

**Issue by IzumiSenaSora** [Bnyro/ConnectYou#179]
### Describe your suggested feature

Merge Contacts if Duplicate Available...
Suggest to merge... And then merge Manually after checking

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Your issue neither contains details why that would be needed nor criteria how to find duplicates nor a suggestion for UI-wise implementation.
I don't see a reason to put efforts into this specific issue.
