### ISSUE TITLE
Settings menu suggestion

### ISSUE THREAD

**Issue by unityastronaut** [Bnyro/ConnectYou#187]
### Describe your suggested feature

I think the settings menu could be improved so I made a mockup. I reorganized the settings into three categories (Appearance, Behavior & Backup) instead of four. I used a segmented button for the theme picker. For the start tab setting I used check boxes, because I think ideally the user could not only select which tab opens on start, but also what tabs are shown at all. Selecting only one should then hide the nav bar indefinitely. (This is a separate feature suggestion for user who only use one tab). Changing the order of the check boxes could then change the order of the tabs. This would combine two settings into one. For the backup location selector I used a segmented button as well, but turned the "none" option into a toggle. If toggled off, this should grey out the whole backup setting making it more intuitive. I also used toggle switches for all on/off settings and added setting explanations in some places. This all closely follows the M3 design guidelines. 

![Settings Menu](https://github.com/Bnyro/ConnectYou/assets/82398591/16c97717-154e-495f-9ce1-ff365c19afc2)
![Screenshot_20230620-174507](https://github.com/Bnyro/ConnectYou/assets/82398591/6fb92b92-5fe4-473e-b19d-fdbc50103732)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by awadhh** [comment]
Set ringtone for single contact - custom ringtone feature would be great, Google contacts has this feature.

**Comment by unityastronaut** [comment]
> Set ringtone for single contact - custom ringtone feature would be great, Google contacts has this feature. Fast scroll using letter is missing, Simple contacts has this.

You sould open seperate feature requests for these suggestions. They cannot be labeled, closed and discussed here...
