### ISSUE TITLE
Data should be grouped

### ISSUE THREAD

**Issue by airon90** [Bnyro/ConnectYou#19]
I suppose that it would be nicer if data are shown in groups. I explain what I mean: now, there is a bubble for each data (phone home, phone work, mobile, email home, email work, ...).I suppose that it should be better to have a bubble for all phones and mobile phones (with specification), all emails, all anniversary dates, ...

**Comment by Bnyro** [comment]
They are already sorted properly, however I don't think it would really look good if we grouped things since we would need to overlay different cards then or not highlight the single fields, which I can't imagine to look good. Thus, not planned.
