### ISSUE TITLE
Uniform Icons 

### ISSUE THREAD

**Issue by unityastronaut** [Bnyro/ConnectYou#192]
### Describe your suggested feature

I'm a huge fan of the "You"-Apps. I use GrapheneOS and the AOSP apps have horrible UI. I think it would look nice to have the same icon style for all of the apps. Same icon color, background color and icon style (Fill or Outline). I created some icons as an example and experimented with gradient and material you colors. What do you think?

![Icons](https://github.com/Bnyro/ConnectYou/assets/82398591/b381bd5a-a1ff-4c1c-adef-4e8189117be0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The icons look awesome in my opinion, thank you for your hard work!

The icons shapes already look awesome in my opinion!

However I'd love to use a bit different colors for the normal icons (second row) than the purple ones because I prefer a bit different color tones personally.
In my opinion, using a dark background would look slightly better for them, I'd really love to use some colors from [Catppuccin](https://github.com/catppuccin/catppuccin#-palette) because I just love its colors from the Mocha theme and think that would look quite well.

And I think it'd be really cool if we could find an icon for [Translate You](https://github.com/Bnyro/TranslateYou) and [Record You](https://github.com/Bnyro/TranslateYou) too, so that all look the same way. Again, thanks for your efforts! :)

**Comment by unityastronaut** [comment]
I added TranslateYOu and RecordYou icons and a fourth row with outline style. Do you prefer fill or outline? I think overall filled is the better choice because it's easier on the eyes, but some of the line icons look nice too.
![Icons](https://github.com/Bnyro/ConnectYou/assets/82398591/387b28d0-7747-4e3a-911a-8a6cfa4e2fa7)

**Comment by Bnyro** [comment]
The filled icons look more uniform because the outlined ones have different stroke widths, which looks a bit odd when having them all next to each other.

**Comment by Bnyro** [comment]
Ah, I just noticed we also have to make all icons look well using the rounded circle shape (like in the first row), so that nothing is getting cut off when using it

**Comment by Bnyro** [comment]
This could be a bit different for the Wall You icon

**Comment by unityastronaut** [comment]
> The filled icons look more uniform because the outlined ones have different stroke widths, which looks a bit odd when having them all next to each other.

You're right. I did the fourth row rather quickly so the stroke is not uniform, but I can fix that. I also need to make the clock icon a little larger. But I think it's good enough to make a decision on what style to go for. The final versions will need some tweaking still.

**Comment by unityastronaut** [comment]
> Ah, I just noticed we also have to make all icons look well using the rounded circle shape (like in the first row), so that nothing is getting cut off when using it

Right. I will test if the icons work with round frames as well. If not we'll have to find an alternative for the WallYou icon.

**Comment by unityastronaut** [comment]
I placed the icons on a round background and added alternative versions for the WallYou icon. I also designed an new WallYou and ConnectYou icon from scratch. We can now decide what style and version we want. For WallYou and ConnectYou I prefer the ones in the second row. 

Unfortunately the Material Symbols from Google Fonts I used for most of the icons are single layer drawings. I can only resize them, not change the stroke width. This is a problem, because I need to make size adjustments to make them fit the icon frames better. For example the TranslateYou icon is to big for the frame. If I scale it down the stroke width would be less than the rest of the icons. Which means, I will have to design every icon from scratch, using the Material Symbols as reference. This will take some time, especially for the more complex ones like TranslateYou.

Also I quite like the light icons in the second row of my first post. What do think about an option to choose between a light version, like I suggested and a dark version, like you suggested similar to the option in LibreTube?

![New Icons](https://github.com/Bnyro/ConnectYou/assets/82398591/2a4eb91c-414a-4923-8e9e-d7b42e1c250b)

**Comment by Bnyro** [comment]
Thank you for your efforts!
With these changes, I do prefer the outlined icons over the filled ones since
1. the translate icon is outlined always anyways
2. they look more minimal than the others

Concerning which ones, the contact and wallpaper icon in row 2 are my preferred ones (as you said too! :) )

Concerning the stroke widths, the ones in lines 1 and 2 already look like they have the same stroke width, that's perfectly fine like so!

Unfortunately, allowing the user to choose which app icon to use is connected to a lot of efforts (needs refactoring for each app) and I really don't want to do that, I'm afraid. I'd be fine with using light icons too when using colors from the Catppuccin Latte theme, for example:
- background: #eff1f5
- gradient color one: #7287fd
- gradient color two: #8839ef
(didn't test the colors, just a quick thought, others from the palette might fit better).

I just feel like the three colors you picked in your first draft don't fit together perfectly, they don't harmonize as good as using a pre-defined color scheme :)

**Comment by unityastronaut** [comment]
I applied the colors you suggested and did some minor tweaking to some of the icons. The difficult part is the TranslateYou icon. I made it smaller by redrawing the "A" with the same stroke width but smaller in size. What do you think? If we want it to be smaller still, I'd have to redraw the Kanji symbol as well...

![Icons](https://github.com/Bnyro/ConnectYou/assets/82398591/106977bf-4300-4401-b3f1-d46b0cce8cd1)

**Comment by Bnyro** [comment]
All icons in the top row look absolutely awesome! I really think they would fit much better than the ones that are filled. If you're fine with all of them in the first row, I'd love it if you could just send me all the SVG files, and I'll apply them for all the apps and publish them with the next release cycle :)
Thanks for all your work, I think it is really awesome to have all the icons align with each other, and they still have their uniqueness to not get mixed up with other apps! <3

**Comment by unityastronaut** [comment]
All icons are final now. I moved the WallYou icon up a little bit in the frame. Also, I think I inverted the two colors in the last version. I used blue on top and purple on bottom this time, because the blue is lighter. The gradient is applied diagonally (left top to right bottom). I could also apply it vertically (top middle to bottom middle), but I think the way it is now looks good. I also made a TranslateYou icon with both Letters having the same size (row 1), which is smaller overall and fits the frame a little better. We can pick between row 1 and 2. After that I will send you the files. What size should they be? I saw that Google Play Store uses 512x512. I'll send them via email or did you have something else in mind?


![Icons](https://github.com/Bnyro/ConnectYou/assets/82398591/054f8658-4aa7-4bdf-952b-6e871efc740b)

**Comment by Bnyro** [comment]
Otherwise, you can also send them to `bnyro@tutanota.com` or to @bnyro:matrix.org.

**Comment by unityastronaut** [comment]
I attached them as a .zip file. Can't wait to see them in action :). If you ever find the time to work on another "You" app, feel free to let me know and I will design a matching icon. Deutsch geht auch, ist mir gerade aufgefallen... :)

[Icons.zip](https://github.com/Bnyro/ConnectYou/files/11918048/Icons.zip)

**Comment by Bnyro** [comment]
Awesome, thank you! I hope I'll find time for applying them to the apps tomorrow, however I'll probably publish new releases for all of them individually and not at the same time, but it shouldn't take too long until all of them use the new icons :)
I don't currently have plans for a new app because I already have enough stuff to work on / maintain currently, but if I do I'll be asking you for a matching icon of course :)
Deutsch würde auch gehen, aber wenn wir in Englisch schreiben können auch andere, die aus welchem Grund auch immer das hier lesen wollen, der Konvo folgen ;)

**Comment by unityastronaut** [comment]
I just noticed I forgot to apply the gradient for the TranslateYou icon diagonally (It's vertically by default). It's barely noticeable. I wouldn't have noticed myself, if I didn't look at the change history by chance. Don't know if it matters enough, but I attached a fixed version just in case. 
[TranslateYou(Fixed).zip](https://github.com/Bnyro/ConnectYou/files/11925587/TranslateYou.Fixed.zip)

**Comment by Bnyro** [comment]
Awesome, thank you so much!

**Comment by Bnyro** [comment]
First one landed: https://github.com/Bnyro/TranslateYou/commit/3507055e577cdf11a10cc38ddf1d0efa4e6a1dca :)
Gonna do the others later if I find the time, I finally got some more time now :)

**Comment by Bnyro** [comment]
If you want to, you can create PRs at all the repos and make a credits section in the README and add yourself for the app icons so that it's transparent who designed them. You don't need to though, as you prefer.

**Comment by Bnyro** [comment]
All icons were replaced now, and should also be updated automatically on F-Droid / IzzyOnDroid once we create a new release.

**Comment by unityastronaut** [comment]
Wow, that was fast. Looks great :). Some of them look a little smaller than before though (eg. WallYou/RecordYou). Did you size them down a little?

**Comment by Bnyro** [comment]
Unfortunately I had to because Android sizes the icons differently. If I wouldn't have done that, older devices would have had issues with the icons, I already had such issues with certain apps before.
(All were scaled down to 55% now, so I hope it's halfway fine).

**Comment by unityastronaut** [comment]
I didn't know about this. I've read some threads about it and it sounds really annoying. I actually used the Play Store and Material Icons guidelines and made the icons exactly 75% the size of the background as suggested. But if they are all sized down equally this should be alright. Could we use the original icon in the readme, because that one is not getting cropped, or do they all have to be the same?

**Comment by Bnyro** [comment]
Yes, surely we can do that. We just need to manually replace the file `fastlane/metadata/android/en-US/images/icon.png`, then F-Droid uses the proper icon too.

**Comment by M00NJ** [comment]
Okay, I will give this a try. I've never opened a PR, but this seems fairly simple. I just have to remove the current png and add a new one. But I just looked at the ConnectYou readme and the icon is from `app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png`, so I will also have to change this to `fastlane/metadata/android/en-US/images/icon.png` for it to work right? The new png should also be higher res and have a round background I think.

**Comment by M00NJ** [comment]
I made the changes and opened a PR. I hope I did everything correctly, because I don't really know how to use GitHub yet. If everything is right, I will do the same for the other repos.

**Comment by Bnyro** [comment]
Looks fine, thanks!

**Comment by Bnyro** [comment]
Thanks for your other PRs!

**Comment by M00NJ** [comment]
I wonder if Obtanium will use the launcher icon or the GitHub readme one. I think it should be the right one. But we'll see :)

**Comment by Bnyro** [comment]
Hey @M00NJ,
ich habe versucht herauszufinden wie ich dich am besten privat erreichen kann, aber weil ich nix gefunden habe schreibe ich dir jetzt einfach mal hier.

Folgendes: Ich habe alle `You`-Apps, die ich erstellt habe, in eine neue GitHub Organisation verschoben, weil die Apps schon lang nicht nur noch mein Projekt sind, sondern auch viele andere dazu maßgeblich beigetragen haben.

Da du die Icons für die Apps designed hast, und in letzter Zeit fleißig an Verbesserungen an `ClockYou` gearbeitet hast, möchte ich dich gerne in die Organisation einladen und dir Berechtigungen geben, um die App `ClockYou` zu verwalten.

Das heißt natürlich nicht dass ich nicht mehr an den Apps arbeiten werde - von mir aus geht alles so weiter wie bisher. Ich möchte nur gerne auch die Beiträge anderer wertschätzen, und die Zusammenarbeit vereinfachen.

Wenn du damit einverstanden bist, schicke ich dir via GitHub Einladungen dafür (kommen wahrscheinlich per E-Mail).

Viele Grüße
Bnyro
