### ISSUE TITLE
How about an new app filesyou for android

### ISSUE THREAD

**Issue by Justauser0** [Bnyro/ConnectYou#199]
### Describe your suggested feature

The app should be able compress and decompress files and open password protected file

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by BluePixel4k** [comment]
@Justauser0 you can use the app "Material Files":
https://www.f-droid.org/en/packages/me.zhanghai.android.files/

**Comment by Justauser0** [comment]
> @Justauser0 you can use the app "Material Files": https://www.f-droid.org/en/packages/me.zhanghai.android.files/

I am looking app like zarchiver which does not use internet and which is available in F-droid or izzyondroid
