### ISSUE TITLE
Add fastlane to Weblate

### ISSUE THREAD

**Issue by airon90** [Bnyro/ConnectYou#21]
I suppose you should add Fastlane data to translation on Weblate so that one can read app description, changelog and onther info in their language

**Comment by Bnyro** [comment]
In my opinion English is sufficient for that, I don't want any volunteers to waste their time by translating those things for the app :)

**Comment by airon90** [comment]
At least the description of the app should be translated in order to let people understand what this app is about

**Comment by Bnyro** [comment]
I disagree, I will soon add screenshots and then everything should be self-explaining.
