### ISSUE TITLE
Please provide this via the Google Play Store.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Bnyro/ConnectYou#213]
### Describe your suggested feature

My rationale is available at https://github.com/Stypox/dicio-android/issues/92#issue-1327604867:

<blockQuote>

The Google Play Store allows users to be more easily able to manage the software that they use than F-Droid does in many ways.

More specifically, the Google Play Store:
* Provides beta programmes,
* Provides a web interface at play.google.com, which allows remote installation,
* Provides a way to easily see reviews, and
* Notifies the user if known-to-be-harmful software (removed from the store) is installed.

</blockQuote>

which F-Droid and *definitely* Accrescent don't.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't have a Google account or want to support that company in any way, therefore not planned.
