### ISSUE TITLE
Add the "Available at F-Droid" image beside IzzyDroid's in ReadMe.

### ISSUE THREAD

**Issue by rokejulianlockhart** [Bnyro/ConnectYou#214]
### Describe your suggested feature

![image](https://mobileapp.bitwarden.com/fdroid/btn.png)

### Other details

https://f-droid.org/packages/com.bnyro.contacts/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please create a PR.

**Comment by rokejulianlockhart** [comment]
@Bnyro, I don't know how to associate an image with a link. I only mentioned it because users currently will think that this app is only available via IzzySoft's repository, which is additional barrier to entry if they don't have that added.
