### ISSUE TITLE
WhatsApp confused by ConnectYou

### ISSUE THREAD

**Issue by HarriBuh** [Bnyro/ConnectYou#23]
I wanted to give this app a chance as it's one of the few ones that uses Google's API, so linking my entries with social messengers like WhatsApp would finally start working again.
Sadly, the linking process went completely wrong, as my contacts linked to wrong Whatsapp ones.

I just checked again and it seems that not every linking went wrong, just the ones whose names or surnames are the same (e.g. "Sarah M" vs. "Sarah P." or "Max S." vs. "Lisa S.").

I take this as a bug.

![markup_1000000833](https://user-images.githubusercontent.com/123186113/215721088-1d600f80-6540-4e4b-a3ef-dca8a63f3052.png)

**Comment by Bnyro** [comment]
What do you mean by "contact linking"? Did you create these contacts inside ConnectYou and they don't appear properly in WhatsApp?
I don't use WhatsApp so I doubt I will be able to help with that.

**Comment by Bnyro** [comment]
Alright, thanks for blaming my app, WhatsApp was never meant to be targeted in specific by Connect You, I won't deal with issues of third party apps.
