### ISSUE TITLE
ConnectYou fails at importing vcf files properly

### ISSUE THREAD

**Issue by HarriBuh** [Bnyro/ConnectYou#25]
Thanks for shutting me down before I could further test my contact importing issue. Got butthurt?

Anyway, the issue does NOT begin with WhatsApp or other apps, your app already fails at importing contacts from an ordinary vcf file properly. I found out about this after opening ConnectYou and already recognizing doubled contacts in my list. So I double checked by doing the same procedure (= import a vcf file into a contact app) with another contact app and voila- no issues.

So maybe you might check inside your code again what could be the real issue here.
Btw: I'm here to help to make your app useful and great, not to destroy it.

ConnectYou right after importing the vcf file (messed up #1)
![markup_1000000841](https://user-images.githubusercontent.com/123186113/215762520-65cdc3e0-ce53-4ef2-b0a0-591f6054a477.png)

Other contact app right after importing the same vcf file (everything fine!)
![markup_1000000842](https://user-images.githubusercontent.com/123186113/215760521-eb5b6b10-e0b1-4a7a-89b7-fd9e2adb2a9f.png)

The same other app after importing the vcf file to ConnectYou first, then exporting it into a new vcf file via ConnectYou and reimporting that file back into the other contact app (messed up #2)
![Screenshot_20230131-133448~2](https://user-images.githubusercontent.com/123186113/215761683-a6d6b47d-b0fb-4ad2-b9cd-26ce5134932c.png)

**Comment by Bnyro** [comment]
For me there is no such issue, believe me I tested all possible scenarios.
Though importing the same file twice will cause duplicated contacts since the app doesn't yet support preventing duplicated contacts by different imports.
Before you complain again, please move to an other app.
