### ISSUE TITLE
Not able add new number to existing contacts 

### ISSUE THREAD

**Issue by Dhangofa** [Bnyro/ConnectYou#33]
I am not able to add a number to existing contacts from dial pad, it is saying no contact app found. But when I try to create new contact from dial pad, then it opens the contact app( connect you)

Please add this feature to add numbers to existing contacts from dialpad

**Comment by Bnyro** [comment]
What are you referring to by dialpad?
Your phone's dialer app? Connect You supports getting opened by Koler and the dialer from LineageOS already.

**Comment by Dhangofa** [comment]
Some times you get a number, you dial the the number from the dial pad( for me its google phone). Now I clicked on the number in the recent call log screen, then click on add to contact. 
After that there should be a option to "Add to Existing Contact"  or create new contact.

In this app always you have to create new contact or go to this contact app then search the contact then edit the contact and add the new number then save.

It is a long process,  for there should be a option to add to existing contact like the below screenshot - 
![Screenshot_2023-02-11-00-03-58-302_com google android dialer-edit](https://user-images.githubusercontent.com/117024745/218171222-67cfc071-3b7b-48d9-88a1-126cf0a206d9.jpg)
![Screenshot_2023-02-11-00-05-17-283_com google android contacts-edit](https://user-images.githubusercontent.com/117024745/218171323-c6ec3deb-90ac-4233-9560-fbdfb6c7da2c.jpg)
![Screenshot_2023-02-11-00-07-25-777_com google android contacts](https://user-images.githubusercontent.com/117024745/218171377-55bcb8fc-e9e3-4aea-8e6b-68eb2e99b322.png)
