### ISSUE TITLE
Directly opening contact instead opening a list of all contacts

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/ConnectYou#34]
When I click to contact in dialer, it shows me a list of all contacts, but not the contact I've clicked

**Comment by Bnyro** [comment]
Can't reproduce using Koler

**Comment by HotarunIchijou** [comment]
@Bnyro you can reproduce it using lineageos dialer and simple dialer

**Comment by Bnyro** [comment]
seems to be fixed with https://github.com/Bnyro/ConnectYou/commit/c6056ba267f623a2742b8a08a309655efc3270ef
(tested with the dialer app of LineageOS)
