### ISSUE TITLE
Preferred number and other improvements

### ISSUE THREAD

**Issue by Surendrajat** [Bnyro/ConnectYou#38]
Things I noticed so far:

- [x] Phone number & Email edit fields should have their own number/email type instead of default string type. It will open relevant keyboard view. #39
- [x] SMS icon used is not the correct SMS icon from material icons. #39
- [ ] Add ability to select a default phone number in case there are multiple numbers present.

**Comment by Surendrajat** [comment]
@Bnyro the last one is still not fixed. Should I open another issue?

**Comment by Bnyro** [comment]
Oh, you edited it?
I thought there only were two points on your list before that both got resolved by the PR :)

**Comment by MahmoudRH** [comment]
I think for the third point we can add a new field for the default number. We can make it take the first entered number by default and then add an option to modify it.

**Comment by Bnyro** [comment]
> I think for the third point we can add a new field for the default number. We can make it take the first entered number by default and then add an option to modify it.
>
Agreed, we should keep it simple by always using the first number available and allow users to modify their order, most likely in the already existing editor.

**Comment by Surendrajat** [comment]
There's a `PREF` key in vCard specification (and in my contact list too, I checked) which tells you the preference of properties(numbers). I think it should be used for this feature.

ref: https://www.rfc-editor.org/rfc/rfc6350#section-5.3

**Comment by Bnyro** [comment]
The number chosen is always the first one of the contact.
You can move a number to the top by long pressing the type field next to it in the editor (e.g. "custom").
The Vcard library we are using doesn't support the `PREF` field, so there's nothing we can do about preferred numbers in Vcards.

**Comment by Surendrajat** [comment]
@Bnyro is it the same library you're using?
https://github.com/mangstadt/ez-vcard/wiki/Version-differences#23-ez-vcards-approach

**Comment by Bnyro** [comment]
Yes, thanks for linking that, with https://github.com/Bnyro/ConnectYou/commit/d42f778773e139b7476f275c9f26389a4e02c16d we should now import numbers being `PREF` as the first one.

**Comment by Surendrajat** [comment]
Thanks @Bnyro! Does it also work for vCard export?

**Comment by Bnyro** [comment]
It should with the most recent commit :)

**Comment by Surendrajat** [comment]
lol.. thanks a lot.
