### ISSUE TITLE
Move to local

### ISSUE THREAD

**Issue by xmha97** [Bnyro/ConnectYou#51]
### Describe your suggested feature

Please add this feature:
- Move to local:
![IMG_20230211_202938_530](https://user-images.githubusercontent.com/23485114/218270997-b101d01c-501f-4e59-ae83-bf3adf6a3131.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment]
Hi, what is "local"? Are the the contacts stored on the SIM card?

**Comment by Donkey-Doug** [comment]
Maybe then rename to "Vault"?
