### ISSUE TITLE
Replace pencil icon on the bottom right with "+" icon

### ISSUE THREAD

**Issue by matchboxbananasynergy** [Bnyro/ConnectYou#53]
### Describe your suggested feature

Currently, the button to create a new contact has the pencil icon, which is commonly used as an "edit" button. It might make sense to instead use a "+" icon, which is taken to mean add a new entry.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I get your point, however, in direct comparison the `Create` button (the pen) looks definitely better than the `Add` button (plus icon) in my opinion. Therefore I don't plan to change the icon used, see the two screenshots below.

![add](https://user-images.githubusercontent.com/82752168/218543562-5cb892b9-f0ce-4cb1-8283-480fb71803a0.png)
![create](https://user-images.githubusercontent.com/82752168/218543563-4ff7d8b1-6e57-4983-990d-e72e32ab6315.png)

**Comment by harishkumarankr2004** [comment]
I know this is closed, but I have to say many users are used to the "+" icon to be the standard to add something and present on every contacts app.
Replacing this with the pencil icon caused confusion.
