### ISSUE TITLE
Support for contact groups

### ISSUE THREAD

**Issue by Tobias-Lauerbach** [Bnyro/ConnectYou#59]
### Describe your suggested feature
It would be great to have an option to organize your contact list in a similar way it works in Nextcloud and the stock Android Contact app (in my case, CalyxOS - the app is close to AOSP).

I think it would have to be in the Caldav standard and/or Android System Contact standard because I can sync the "Labels" with DavX5 and can use both the handy and the Nextcloud ("Groups") to filter with them.

### Other details
Personally, this helps me a lot to assign people with common names to the appropriate groups of people / places I know them from.

When it comes to implementation, I have two ideas:
1. as an additional filter option in the search bar (in the same Place as sorting first and last name).
2. as an alternative to the "Local" tab ⇾ "Groups" with a similar interface to select the group as in picture 2, when you then select one of the groups you get the filtered list of contacts.
The previous functions of the "Local" tab could be displayed in the list of groups above as a highlighted group, through which you can then open the local contacts. 

I would personally find the second variant more intuitive, but there are certainly other or even better implementations.

In the following example, the group at the bottom is called "Service".

Picture 1:
![Screenshot_20230215-221051](https://user-images.githubusercontent.com/62332598/219168344-c2d071fa-03d2-4d34-af76-64a273085fa1.png)

Picture 2:
![Screenshot_20230215-221011](https://user-images.githubusercontent.com/62332598/219168398-7fa26565-192b-48a7-899c-fc75b8330ba0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please write in German next time, reading that quality of English is a pain, no front.

**Comment by Bnyro** [comment]
And by labels you probably mean contact groups.

**Comment by Tobias-Lauerbach** [comment]
> Please write in German next time, reading that quality of English is a pain, no front.

I have revised my contribution, the last variant was really bad sorry, I hope it is now much more readable.

Also, I would like to say thanks for the great development of the app, it has long lacked a usable FOSS address book.

**Comment by Bnyro** [comment]
I think the best way would be to add that as a filter to the sort menu (which will be replaced with a dialog), that will make it the most comfortable, especially with #59 being implemented too.

**Comment by Tobias-Lauerbach** [comment]
> 

Yes a dialog would also work well. 
My thought with the tabs was, that it would be less hidden, but it quiets hides the Local contacts which would also be bad, but  Local contacts as part of groups would be more self explaining / easy to find in my mind.
But at the end it comes down to what will be used more, and I will admit that I'm personally not having any real use of Local contacts, and that for may also be a bit biased... (a possibility would be to Make a toggle Option in the Settings for the tabs where you can choose to show and hide the local or groups tab)

I hope it doesn't sound disrespectful or so, I  just think discussion is important, but I could also understand if it is annoying... (Just say it, it is your project and your choice 😄)

(#59 is this issue, did you wanted to mention another one, or am I not getting something? sorry)

**Comment by Bnyro** [comment]
Oh, yes, sorry, I wanted to mention #57.
I've heard from some people that they only use CY because of / for the local contacts feature, so I think it would be weird to add a tab for it only for the device contacts.

**Comment by Tobias-Lauerbach** [comment]
>
Yes that makes scene, then the sorting/filter menu would probably be the best way, to combine both features.
I am already looking forward to the implementation (if possible)
