### ISSUE TITLE
Swipe function

### ISSUE THREAD

**Issue by xmha97** [Bnyro/ConnectYou#62]
### Describe your suggested feature

I want to change the swipe function.
By default, the contacts will be delete by swiping.
I want to change the function to call.
(Swipe to make a call)
Also add an option to disable swiping.
Sorry for my bad English
Thanks.

![Screenshot_2023-02-19-01-49-39-848_com bnyro contacts](https://user-images.githubusercontent.com/23485114/219901982-fb77d683-c099-47a6-adbc-f0f8b649fb63.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that since
1. Some contacts don't even have a phone number
2. You wouldn't see the number before calling
3. Calls are not handled by CY

**Comment by xmha97** [comment]
> No plans for that since
> 
>     1. Some contacts don't even have a phone number
> 
>     2. You wouldn't see the number before calling
> 
>     3. Calls are not handled by CY

Thanks for your reply @Bnyro 
I read your reasons.

At least add an option so we can disable this feature
It's really annoying for me.
