### ISSUE TITLE
Crash on import vcard

### ISSUE THREAD

**Issue by 0xlne** [Bnyro/ConnectYou#64]
### Steps to reproduce

1. Select Import vcard
2. Select vcard from internal storage

### Expected behavior

1. List of contacts to appear 

### Actual behavior

1. Crash/app disappears

### Connect You version

1.0

### Android version

13

### Other details

Device = Xiaomi Mix Fold 2
The vcard is an export from OpenContacts (https://gitlab.com/sultanahamer/OpenContacts)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I can't reproduce that, please build the app on your own in Android Studio and provide a crash log since you probably don't want to share the vcard file.

**Comment by 0xlne** [comment]
Let me check if I can clear my DB, put some bogus contacts & export.
Will be back to report.
n.b. updated to 1.1 & the issue is present there as well.

**Comment by 0xlne** [comment]
02-21 10:30:16.123  4509  5629 W RecentsModel: getRunningTask   taskInfo=TaskInfo{userId=0 taskId=3563 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.bnyro.contacts/.ui.MainActivity } baseActivity=ComponentInfo{com.bnyro.contacts/com.bnyro.contacts.ui.MainActivity} topActivity=ComponentInfo{com.bnyro.contacts/com.bnyro.contacts.ui.MainActivity} origActivity=null realActivity=ComponentInfo{com.bnyro.contacts/com.bnyro.contacts.ui.MainActivity} numActivities=1 lastActiveTime=2819848271 supportsSplitScreenMultiWindow=true supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=200 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@67608bb} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=0 displayCutoutSafeInsets=Rect(0, 86 - 0, 0) topActivityInfo=ActivityInfo{28ce1d8 com.bnyro.contacts.ui.MainActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isSleeping=false topActivityInSizeCompat=false topActivityInMiuiSizeCompat=false topActivityEligibleForLetterboxEducation= false locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden mIsCastMode=false}
02-21 10:30:16.123  4509  5629 W RecentsModel: getTaskInfoIgnoreHomeAndFreeform   taskInfo=ComponentInfo{com.bnyro.contacts/com.bnyro.contacts.ui.MainActivity}
02-21 10:30:16.123  4509  5629 E ActivityManagerWrapper: get all recent tasks force including 3563
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: size=7
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: mainTaskId=3563   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.bnyro.contacts/com.bnyro.contacts.ui.MainActivity} }
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: mainTaskId=3562   userId=0   baseIntent=Intent { act=android.settings.SETTINGS flag=335544320 cmp=ComponentInfo{com.android.settings/com.android.settings.MiuiSettings} }
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: mainTaskId=3557   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.evildayz.code.telegraher2/org.telegram.messenger.DefaultIcon} }
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: mainTaskId=3469   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{us.spotco.fennec_dos/us.spotco.fennec_dos.App} }
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: mainTaskId=3553   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=268484608 cmp=ComponentInfo{network.loki.messenger/org.thoughtcrime.securesms.home.HomeActivity} }
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: mainTaskId=3547   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{playorna.com.orna/playorna.com.orna.Index} }
02-21 10:30:16.125  4509  5629 E ActivityManagerWrapper: getRecentTasks: mainTaskId=3548   userId=0   baseIntent=Intent { act=android.intent.action.MAIN flag=270532608 cmp=ComponentInfo{com.angrydoughnuts.android.alarmclock/com.angrydoughnuts.android.alarmclock.AlarmClockActivity} }
02-21 10:30:16.157  2909  2909 E AndroidRuntime: FATAL EXCEPTION: main
02-21 10:30:16.157  2909  2909 E AndroidRuntime: Process: com.bnyro.contacts, PID: 2909
02-21 10:30:16.157  2909  2909 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String f4.a1.n' on a null object reference in method 'java.util.ArrayList u3.l.b(java.lang.String)'
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at u3.l.b(SourceFile:74)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at u3.g.c(SourceFile:114)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at r3.f.k(SourceFile:45)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at r3.f.Z(SourceFile:16)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at i3.c$a.k(Unknown Source:28)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at n4.a.u(Unknown Source:8)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at c5.n0.run(Unknown Source:100)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at kotlinx.coroutines.internal.f.run(Unknown Source:11)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)
02-21 10:30:16.157  2909  2909 E AndroidRuntime: 	Suppressed: c5.l0: [x1{Cancelling}@42d080d, Dispatchers.Main.immediate]
02-21 10:30:16.154  2909  2909 W .bnyro.contacts: type=1400 audit(0.0:726304): avc: denied { search } for name="miuilog" dev="dm-43" ino=380 scontext=u:r:untrusted_app:s0:c91,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.bnyro.contacts
02-21 10:30:16.154  2909  2909 W .bnyro.contacts: type=1400 audit(0.0:726305): avc: denied { search } for name="miuilog" dev="dm-43" ino=380 scontext=u:r:untrusted_app:s0:c91,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.bnyro.contacts
02-21 10:30:16.154  2909  2909 W .bnyro.contacts: type=1400 audit(0.0:726306): avc: denied { search } for name="miuilog" dev="dm-43" ino=380 scontext=u:r:untrusted_app:s0:c91,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.bnyro.contacts
02-21 10:30:16.154  2909  2909 W .bnyro.contacts: type=1400 audit(0.0:726307): avc: denied { search } for name="miuilog" dev="dm-43" ino=380 scontext=u:r:untrusted_app:s0:c91,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.bnyro.contacts
02-21 10:30:16.154  2909  2909 W .bnyro.contacts: type=1400 audit(0.0:726308): avc: denied { search } for name="miuilog" dev="dm-43" ino=380 scontext=u:r:untrusted_app:s0:c91,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.bnyro.contacts
02-21 10:30:16.154  2909  2909 W .bnyro.contacts: type=1400 audit(0.0:726309): avc: denied { search } for name="miuilog" dev="dm-43" ino=380 scontext=u:r:untrusted_app:s0:c91,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.bnyro.contacts
02-21 10:30:16.154  2909  2909 W .bnyro.contacts: type=1400 audit(0.0:726310): avc: denied { getattr } for path="/data/miuilog" dev="dm-43" ino=380 scontext=u:r:untrusted_app:s0:c91,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.bnyro.contacts
02-21 10:30:16.158  8796  8829 W MQSEventManager: jeoccur
02-21 10:30:16.160  8796  9244 D DigestGenerator: digest=============com.bnyro.contactsjava.lang.NullPointerException: Attempt to read from field 'java.lang.String XX.XX.n' on a null object reference in method 'java.util.ArrayList u.l.b(java.lang.String)'
02-21 10:30:16.160  8796  9244 D DigestGenerator: at u.l.b(SourceFile:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at u.g.c(SourceFile:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at r.f.k(SourceFile:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at r.f.Z(SourceFile:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at i.c$a.k(Unknown Source:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at n.a.u(Unknown Source:)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at XX.n.run(Unknown Source:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at kotlinx.coroutines.internal.f.run(Unknown Source:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at kotlinx.coroutines.scheduling.j.run(Unknown Source:)
02-21 10:30:16.160  8796  9244 D DigestGenerator: at kotlinx.coroutines.scheduling.a$a.run(SourceFile:XX)
02-21 10:30:16.160  8796  9244 D DigestGenerator: Suppressed: XX.l: [x{Cancelling}XX, Dispatchers.Main.immediate]
02-21 10:30:16.161  8796  9244 W MQSEventManager: begin to storeEvent
02-21 10:30:16.162  8796  9244 W DatabaseUtils: je not allow store to db.
02-21 10:30:16.162  8796  9244 D MQSRuleManager: Begin to match mqsas rules
02-21 10:30:16.162  8796  9244 W MQSRuleManager: Data reporting not allowed，do not match rules.
02-21 10:30:16.162  8796  9244 W MQSEventManager: Method in addExceptionCommetAction, actionCommand is null!
02-21 10:30:16.162  8796  9244 W MQSActionExecutor: action is null!
02-21 10:30:16.162  8796  9244 W MQSEventManager: executeResult is 2
02-21 10:30:16.164  2587  5023 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-21 10:30:16.170  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=1
02-21 10:30:16.170  1501  1501 I MI-SF   : surfaceflinger setreAffinity reTid=2472
02-21 10:30:16.170  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=0
02-21 10:30:16.171  1501  3165 I SurfaceFlinger: setTransactionState focusRequest transactionId:11111081945933 frontWin:<null>
02-21 10:30:16.171  2909  2909 I Process : Process is going to kill itself!
02-21 10:30:16.171  2909  2909 I Process : java.lang.Exception
02-21 10:30:16.171  2909  2909 I Process : 	at android.os.Process.killProcess(Process.java:1344)
02-21 10:30:16.171  2909  2909 I Process : 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
02-21 10:30:16.171  2909  2909 I Process : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
02-21 10:30:16.171  2909  2909 I Process : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-21 10:30:16.171  2909  2909 I Process : 	at c5.b0.a(SourceFile:73)
02-21 10:30:16.171  2909  2909 I Process : 	at g.n0.p(SourceFile:15)
02-21 10:30:16.171  2909  2909 I Process : 	at c5.x1.f0(Unknown Source:2)
02-21 10:30:16.171  2909  2909 I Process : 	at c5.l1.X(SourceFile:105)
02-21 10:30:16.171  2909  2909 I Process : 	at c5.l1.s0(SourceFile:229)
02-21 10:30:16.171  2909  2909 I Process : 	at c5.l1.j0(SourceFile:5)
02-21 10:30:16.171  2909  2909 I Process : 	at c5.a.u(SourceFile:14)
02-21 10:30:16.171  2909  2909 I Process : 	at n4.a.u(Unknown Source:31)
02-21 10:30:16.171  2909  2909 I Process : 	at c5.n0.run(Unknown Source:100)
02-21 10:30:16.171  2909  2909 I Process : 	at android.os.Handler.handleCallback(Handler.java:942)
02-21 10:30:16.171  2909  2909 I Process : 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 10:30:16.171  2909  2909 I Process : 	at android.os.Looper.loopOnce(Looper.java:210)
02-21 10:30:16.171  2909  2909 I Process : 	at android.os.Looper.loop(Looper.java:299)
02-21 10:30:16.171  2909  2909 I Process : 	at android.app.ActivityThread.main(ActivityThread.java:8252)
02-21 10:30:16.171  2909  2909 I Process : 	at java.lang.reflect.Method.invoke(Native Method)
02-21 10:30:16.171  2909  2909 I Process : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
02-21 10:30:16.171  2909  2909 I Process : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
02-21 10:30:16.171  2909  2909 I Process : Sending signal. PID: 2909 SIG: 9
02-21 10:30:16.173  2587  8678 D CompatibilityInfo: mCompatibilityFlags - 4
02-21 10:30:16.173  2587  8678 D CompatibilityInfo: applicationDensity - 290
02-21 10:30:16.173  2587  8678 D CompatibilityInfo: applicationScale - 1.0
02-21 10:30:16.176  2587  5023 D CompatibilityInfo: mCompatibilityFlags - 4
02-21 10:30:16.176  2587  5023 D CompatibilityInfo: applicationDensity - 290
02-21 10:30:16.176  2587  5023 D CompatibilityInfo: applicationScale - 1.0
02-21 10:30:16.177  1501  1501 I SurfaceFlinger: transactionIsReadyToBeApplied focusRequest transactionId:11111081945933
02-21 10:30:16.177  1501  1501 I SurfaceFlinger: addInputWindowCommands hasChanges
02-21 10:30:16.178  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=1
02-21 10:30:16.178  1501  1501 I MI-SF   : surfaceflinger setreAffinity reTid=2472
02-21 10:30:16.178  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=0
02-21 10:30:16.189  2587  5023 D CompatibilityInfo: mCompatibilityFlags - 4
02-21 10:30:16.189  2587  5023 D CompatibilityInfo: applicationDensity - 290
02-21 10:30:16.189  2587  5023 D CompatibilityInfo: applicationScale - 1.0
02-21 10:30:16.191  2587 10978 W InputManager-JNI: Input channel object '4fef91 com.bnyro.contacts/com.bnyro.contacts.ui.MainActivity (client)' was disposed without first being removed with the input manager!
02-21 10:30:16.191  2587  2774 I libprocessgroup: Successfully killed process cgroup uid 10347 pid 2909 in 0ms
02-21 10:30:16.191  2587  4168 E ProcessManager: error write exception log
02-21 10:30:16.192  1217  1217 I Zygote  : Process 2909 exited due to signal 9 (Killed)

**Comment by Bnyro** [comment]
Looks like all the class names are obfuscated so the log isn't really useful, did you try it with a debug/CI build (under GitHub actions of the repo)?

**Comment by 0xlne** [comment]
> Looks like all the class names are obfuscated so the log isn't really useful, did you try it with a debug/CI build (under GitHub actions of the repo)?

I just captured a logcat on my device using the f-droid build.
Is the one in releases a debug or release variant?

**Comment by Bnyro** [comment]
Builds on F-Droid are release variants, so please try to get the error log with https://github.com/Bnyro/ConnectYou/actions/runs/4234438273

**Comment by 0xlne** [comment]
02-21 19:57:33.597  8796  8845 W MQSEventManager: jeoccur
02-21 19:57:33.600  8796  9244 D DigestGenerator: digest=============com.bnyro.contacts.debugjava.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ezvcard.property.StructuredName.getGiven()' on a null object reference
02-21 19:57:33.600  8796  9244 D DigestGenerator: at com.bnyro.contacts.util.VcardHelper.importVcard(VcardHelper.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at com.bnyro.contacts.util.ExportHelper.importContacts(ExportHelper.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at com.bnyro.contacts.ui.models.ContactsModel$importVcf$.invokeSuspend(ContactsModel.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at com.bnyro.contacts.ui.models.ContactsModel$importVcf$.invoke(Unknown Source:)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at com.bnyro.contacts.ui.models.ContactsModel$importVcf$.invoke(Unknown Source:)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at com.bnyro.contacts.ext.WithIOKt$withIO$$.invokeSuspend(WithIO.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:XX)
02-21 19:57:33.600  8796  9244 D DigestGenerator: Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}XX, Dispatchers.Main.immediate]
02-21 19:57:33.603  8796  9244 W MQSEventManager: begin to storeEvent
02-21 19:57:33.603  8796  9244 W DatabaseUtils: je not allow store to db.
02-21 19:57:33.603  8796  9244 D MQSRuleManager: Begin to match mqsas rules
02-21 19:57:33.603  8796  9244 W MQSRuleManager: Data reporting not allowed，do not match rules.
02-21 19:57:33.603  8796  9244 W MQSEventManager: Method in addExceptionCommetAction, actionCommand is null!
02-21 19:57:33.603  8796  9244 W MQSActionExecutor: action is null!
02-21 19:57:33.603  8796  9244 W MQSEventManager: executeResult is 2
02-21 19:57:33.607  2587 10978 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
02-21 19:57:33.612 27782 27782 I Process : Process is going to kill itself!
02-21 19:57:33.612 27782 27782 I Process : java.lang.Exception
02-21 19:57:33.612 27782 27782 I Process : 	at android.os.Process.killProcess(Process.java:1344)
02-21 19:57:33.612 27782 27782 I Process : 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:181)
02-21 19:57:33.612 27782 27782 I Process : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
02-21 19:57:33.612 27782 27782 I Process : 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:61)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:196)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
02-21 19:57:33.612 27782 27782 I Process : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
02-21 19:57:33.612 27782 27782 I Process : 	at android.os.Handler.handleCallback(Handler.java:942)
02-21 19:57:33.612 27782 27782 I Process : 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 19:57:33.612 27782 27782 I Process : 	at android.os.Looper.loopOnce(Looper.java:210)
02-21 19:57:33.612 27782 27782 I Process : 	at android.os.Looper.loop(Looper.java:299)
02-21 19:57:33.612 27782 27782 I Process : 	at android.app.ActivityThread.main(ActivityThread.java:8252)
02-21 19:57:33.612 27782 27782 I Process : 	at java.lang.reflect.Method.invoke(Native Method)
02-21 19:57:33.612 27782 27782 I Process : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
02-21 19:57:33.612 27782 27782 I Process : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
02-21 19:57:33.612 27782 27782 I Process : Sending signal. PID: 27782 SIG: 9
02-21 19:57:33.616  2587 11045 D CompatibilityInfo: mCompatibilityFlags - 4
02-21 19:57:33.616  2587 11045 D CompatibilityInfo: applicationDensity - 290
02-21 19:57:33.616  2587 11045 D CompatibilityInfo: applicationScale - 1.0
02-21 19:57:33.616  1501  2471 I SurfaceFlinger: setTransactionState focusRequest transactionId:11111081987780 frontWin:<null>
02-21 19:57:33.617  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=1
02-21 19:57:33.617  1501  1501 I MI-SF   : surfaceflinger setreAffinity reTid=2472
02-21 19:57:33.617  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=0
02-21 19:57:33.617  2587 10978 D CompatibilityInfo: mCompatibilityFlags - 4
02-21 19:57:33.617  2587 10978 D CompatibilityInfo: applicationDensity - 290
02-21 19:57:33.617  2587 10978 D CompatibilityInfo: applicationScale - 1.0
02-21 19:57:33.624  1501  1501 I SurfaceFlinger: transactionIsReadyToBeApplied focusRequest transactionId:11111081987780
02-21 19:57:33.624  1501  1501 I SurfaceFlinger: addInputWindowCommands hasChanges
02-21 19:57:33.625  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=1
02-21 19:57:33.625  1501  1501 I MI-SF   : surfaceflinger setreAffinity reTid=2472
02-21 19:57:33.625  1501  1501 I MI-SF   : surfaceflinger setAffinity mode=0
02-21 19:57:33.628  2587 10978 D CompatibilityInfo: mCompatibilityFlags - 4
02-21 19:57:33.628  2587 10978 D CompatibilityInfo: applicationDensity - 290
02-21 19:57:33.628  2587 10978 D CompatibilityInfo: applicationScale - 1.0
02-21 19:57:33.631  2587 10978 D CompatibilityInfo: mCompatibilityFlags - 4
02-21 19:57:33.631  2587 10978 D CompatibilityInfo: applicationDensity - 290
02-21 19:57:33.631  2587 10978 D CompatibilityInfo: applicationScale - 1.0
02-21 19:57:33.633  2587  3125 W InputManager-JNI: Input channel object 'dc9c0d1 com.bnyro.contacts.debug/com.bnyro.contacts.ui.MainActivity (client)' was disposed without first being removed with the input manager!

**Comment by Bnyro** [comment]
Oh, I see the issue.

**Comment by 0xlne** [comment]
I confirm it's fixed in 1.2. Thank you!

**Comment by tsiflimagas** [comment]
I'm getting this crash importing contacts I've exported using ConnectYou on v3.0. Here it is https://katb.in/ebujibivosa.
