### ISSUE TITLE
Adding a phone field causes data to shift

### ISSUE THREAD

**Issue by Peter-Harmann** [Bnyro/ConnectYou#70]
### Steps to reproduce

Have a contach with a phone number and email
Tap + to add another number

### Expected behavior

Empty field for new number appears

### Actual behavior

The new number field has the email in it and email field becomes empty

### Connect You version

1.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by githububub** [comment]
Can reproduce. If there exists additional entries (e.g. Address) then those entries are duplicated and pushed down the stack accordingly.
