### ISSUE TITLE
Existing groups not found

### ISSUE THREAD

**Issue by Primokorn** [Bnyro/ConnectYou#74]
### Steps to reproduce

Hello,
I just upgraded to v2.0.
I have several group contacts but none are available.
I see no filter option and contacts are not assigned to a group.
I synchronize my contacts from Nextcloud through Davx5.

Thank you.

### Expected behavior

My existing groups should be available.
I should be able to filter them since they do exist.

### Actual behavior

No existing groups. I can only create new ones. Will they be synchronized?

### Connect You version

2.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We're using the official Android System API for contact groups. Groups can be filtered when clicking the sort menu inside the search bar (only visible if there are groups available). Groups without members are not shown.
I'm not familiar with Nextcloud and DavX5, they're synced if they use the same Android API too. Groups in CY are compatible with the AOSP contacts app, thus they work as intended.

**Comment by Primokorn** [comment]
I guess it was a sync issue. It's working fine.
