### ISSUE TITLE
Send an email to a group

### ISSUE THREAD

**Issue by Primokorn** [Bnyro/ConnectYou#76]
### Describe your suggested feature

Hello,
After selecting a group, it would be great to able to have an email icon to send an email to all those recipients.
Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however there currently are no plans for adding support for that since something like that should be handled with an email client instead as per my imagination.
