### ISSUE TITLE
[Feature Request] [UI] Colorful contact icons

### ISSUE THREAD

**Issue by fellinir** [Bnyro/ConnectYou#79]
## Describe your suggested feature
While I do love the material you concept, the thing which isn't completely appealing to me is to see many boring icons, all similar to each other. In fact, I enjoy how randomly colorful are the icons in the stock Contact App from LOS:

![Colorful icons](https://i.imgur.com/WMCm87q.png)

Would you please consider adding an option to make the icons colorful, while all of the remaining UI elements follow the Material you palette? 

## Other details
No response

## Acknowledgements
- [x] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open source issues.

- [x] I have written a short but informative title.

- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't want to add too many small options that would probably only be used by very few people, so I wonder whether anyone else except fellinir would be interested in having an option for that?
