### ISSUE TITLE
Disabling right swipe gesture

### ISSUE THREAD

**Issue by Donkey-Doug** [Bnyro/ConnectYou#80]
### Describe your suggested feature

Please make it possible to disable the swipe right to delete functionality. I keep triggering it accidentally. Also, deleting contacts is not something that I do so often I need a quick gesture. 

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment]
I am happy when the feature is removed.

**Comment by Bnyro** [comment]
Adding an option for it doesn't make sense, so the best way is to remove the gesture totally I guess.
