### ISSUE TITLE
Exit contact selection

### ISSUE THREAD

**Issue by Donkey-Doug** [Bnyro/ConnectYou#82]
### Describe your suggested feature

After I long press on a contact, I enter a "contact selection" mode. The only way to exit this mode is by:

1. closing the app
2. performing an action like deleting a contact

There should be a way to exit this mode, preferably the back button. Currently the back button closes the app entirely

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can press the checkbox at the top left twice which will deselect all contacts and leave the selection mode. An other way would be to manually deselect all selected contacts, as the selection layout is only visible while at least one contact is selected.
