### ISSUE TITLE
Editing contact and then going back decrements Event dates by 1

### ISSUE THREAD

**Issue by brendanfattig** [Bnyro/ConnectYou#84]
### Steps to reproduce

1. Create contact with an event set to some date. 
2. (Also note that the intended date is not the one that is selected. Probably a related bug but different situation)
3. Save contact. 
4. Press edit contact button
5. Observe decremented event date in edit contact details view. 
6. Input back gesture (or press). 
7. Observe that the decremented date is now saved. 
8. Repeat until your contact’s birthday is now in 800 CE. 

### Expected behavior

Event dates should not decrement. 

### Actual behavior

The date of the event decrements. 

### Connect You version

2.1

### Android version

Android 13

### Other details

What’s interesting is that going back shouldn’t save any edited contact details but the event date still decrements without saving. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by brendanfattig** [comment]
Another thing I forgot to mention was that the date selection UI has overlapping columns. I can open another issue for that if needed.

**Comment by Nacho8347** [comment]
Also having the same issue.

**Comment by Bnyro** [comment]
> Another thing I forgot to mention was that the date selection UI has overlapping columns. I can open another issue for that if needed.
>
That's an issue of the library we're using unfortunately, waiting for them to fix it soon hopefully.

**Comment by voidlesity** [comment]
Any updates on this?

I am still having this issue (almost opened a new issue)

**Comment by voidlesity** [comment]
Using version 11.3 (33) on Android 16

**Comment by MEdrum** [comment]
I'm having the same issue for a while now (Version 11.3 on GrapheneOS)

My guess would be, that timezones are either only handled correctly when reading or when saving the dates so that i.e.
16.05.2026 (0:00) becomes 
15.05.2026 (23:00) when in GMT + 1

Or it's handled as a date with timezones both times, but the date contact field stores dates without timezone information.

**Comment by MEdrum** [comment]
The bug is still present in Version 12.0
