### ISSUE TITLE
Move buttons to the bottom

### ISSUE THREAD

**Issue by Donkey-Doug** [Bnyro/ConnectYou#86]
### Describe your suggested feature

![Screenshot_20230302-190111_Connect You](https://user-images.githubusercontent.com/50382414/222513075-490d9941-6a34-4177-adb3-7838dfe406b2.png)

I think these buttons could be moved to the bottom. This makes one handed one easier.

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I agree with mbs, moving them to the bottom is not more UX friendly, for example if a contact has entries filling the whole page those actions wouldn't even be visible at first place.
