### ISSUE TITLE
Improve date picker

### ISSUE THREAD

**Issue by cYDN48** [Bnyro/ConnectYou#90]
### Describe your suggested feature

Several issues with the date picker:
1. Too much padding at the top and above the reset and ok buttons make it look a bit off. (See screenshot in 2.)
2. There's not enough width for all seven weekdays, so Saturday and Sunday overlap. ([Screenshot](https://user-images.githubusercontent.com/96789053/222992285-45c203c4-6cd7-4bd9-ba27-70bf230fa713.png))
3. Additionally in landscape mode there's not enough height, so not all days are visible. ([Screenshot](https://user-images.githubusercontent.com/96789053/222992509-73dc4cfa-219f-4ae3-9122-c1ec14f55751.png))
4. The previous month visibly appears and disappears when you swipe gently. This does not happen with the next month. ([Video](https://user-images.githubusercontent.com/96789053/222992574-a5031651-77fa-4322-b801-93c6abf9f7c4.mp4))
5. Swiping between months is too sensitive ([Video](https://user-images.githubusercontent.com/96789053/222992808-8b20086c-1eca-4307-b89c-70f6884de7c3.mp4), I barely moved my finger)
6. Swiping to the previous month immediately updates the current month, but swiping to the next month takes like half a second to update ([Video](
https://user-images.githubusercontent.com/96789053/222992712-1c95a8aa-32b8-4991-a424-96ee6f82b2c1.mp4))
7. The height of the date picker doesn't adjust when you switch between calendar and text field. Both results don't look good. ([Screenshot 1](https://user-images.githubusercontent.com/96789053/222992951-edb3b981-2432-46ca-a16b-85a4bfa1a502.png), [Screenshot 2](https://user-images.githubusercontent.com/96789053/222992955-1f161a47-4927-4626-9145-e1e6ad25f14b.png))

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for spending so much time on the issue and looking for all the details, I really appreciate that!
However, we're using the `DatePicker` by the Material Design 3 Jetpack Compose library (see https://m3.material.io/components/date-pickers/overview) and wrap it into a `DatePickerDialog` which is the official, recommended way of displaying a date picker in Jetpack Compose.
Unfortunately, the date picker is still experimental in Jetpack Compose, so the best thing we can do is to wait for future updates of the Material design library that might fix these issues one by one.
